apiVersion: apps/v1
kind: Deployment
metadata:
  name: isabelapires-recommender-playlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: isabelapires-recommender-playlist
  template:
    metadata:
      labels:
        app: isabelapires-recommender-playlist
    spec:
      containers:
        - name: isabelapires-recommender
          image: isabelaferreira/ml-model:0.1
          ports:
            - containerPort: 32187
          volumeMounts:
            - name: isabelapires-shared-pvc
              mountPath: "/recommender/shared"
        - name: isabelapires-webservice
          image: isabelaferreira/flask-webservice:0.1
          ports:
            - containerPort: 32187
          volumeMounts:
            - name: isabelapires-shared-pvc
              mountPath: "/app/shared"
      volumes:
        - name: isabelapires-shared-pvc
          persistentVolumeClaim:
            claimName: isabelapires-shared-pvc
