apiVersion: v1
kind: Service
metadata:
  name: isabelapires-service
spec:
  selector:
    app: isabelapires-recommender-playlist
  ports:
    - protocol: TCP
      nodePort: 32187
      port: 32187
      targetPort: 32187
  type: LoadBalancer